spring:
  application:
    name: search-books

  profiles:
    active: prod

  jpa:
    show-sql: ${JPA_SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: true

  cache:
    type: redis

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

server:
  port: 8080
  forward-headers-strategy: framework
  tomcat:
    remoteip:
      remote-ip-header: x-forwarded-for
      protocol-header: x-forwarded-proto
      internal-proxies: 127\.0\.0\.1|::1|0:0:0:0:0:0:0:1

api:
  google-books:
    base-url: https://www.googleapis.com/books/v1
    api-key: ${GOOGLE_BOOKS_API_KEY}
    timeout: 30s

ocr:
  tesseract:
    data-path: ${OCR_TESSERACT_DATA_PATH:src/main/resources/tessdata}
    language: ${OCR_TESSERACT_LANGUAGE:eng}

logging:
  level:
    com.search.books: ${LOG_LEVEL_APP:info}